-- Commonwax v0.0.1 initial schema. Generated from schema.prisma.

CREATE TYPE "Role" AS ENUM ('OWNER', 'ADMIN', 'MEMBER');
CREATE TYPE "RequestStatus" AS ENUM ('OPEN', 'CLAIMED', 'FULFILLED', 'CANCELLED');
CREATE TYPE "UploadStatus" AS ENUM ('STAGED', 'SCANNING', 'IMPORTED', 'FAILED');
CREATE TYPE "ActivityType" AS ENUM ('MUSIC_ADDED', 'MEMBER_JOINED', 'REQUEST_CREATED', 'REQUEST_CLAIMED', 'REQUEST_FULFILLED');

CREATE TABLE "User" ("id" UUID PRIMARY KEY, "email" TEXT NOT NULL UNIQUE, "displayName" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Library" ("id" UUID PRIMARY KEY, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Membership" ("id" UUID PRIMARY KEY, "userId" UUID NOT NULL REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE, "libraryId" UUID NOT NULL REFERENCES "Library"("id") ON DELETE CASCADE ON UPDATE CASCADE, "role" "Role" NOT NULL DEFAULT 'MEMBER', "permissionOverrides" JSONB, "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE("userId", "libraryId"));
CREATE INDEX "Membership_libraryId_idx" ON "Membership"("libraryId");
CREATE TABLE "Session" ("id" UUID PRIMARY KEY, "tokenHash" TEXT NOT NULL UNIQUE, "userId" UUID NOT NULL REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE, "expiresAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "Session_userId_idx" ON "Session"("userId"); CREATE INDEX "Session_expiresAt_idx" ON "Session"("expiresAt");
CREATE TABLE "Invitation" ("id" UUID PRIMARY KEY, "tokenHash" TEXT NOT NULL UNIQUE, "libraryId" UUID NOT NULL REFERENCES "Library"("id") ON DELETE CASCADE ON UPDATE CASCADE, "createdById" UUID NOT NULL REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "acceptedById" UUID REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE, "role" "Role" NOT NULL DEFAULT 'MEMBER', "expiresAt" TIMESTAMP(3) NOT NULL, "acceptedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "Invitation_libraryId_idx" ON "Invitation"("libraryId");
CREATE TABLE "Artist" ("id" UUID PRIMARY KEY, "libraryId" UUID NOT NULL REFERENCES "Library"("id") ON DELETE CASCADE ON UPDATE CASCADE, "navidromeId" TEXT NOT NULL, "name" TEXT NOT NULL, "albumCount" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, UNIQUE("libraryId", "navidromeId"));
CREATE INDEX "Artist_libraryId_name_idx" ON "Artist"("libraryId", "name");
CREATE TABLE "Album" ("id" UUID PRIMARY KEY, "libraryId" UUID NOT NULL REFERENCES "Library"("id") ON DELETE CASCADE ON UPDATE CASCADE, "artistId" UUID NOT NULL REFERENCES "Artist"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "navidromeId" TEXT NOT NULL, "title" TEXT NOT NULL, "year" INTEGER, "genre" TEXT, "songCount" INTEGER NOT NULL DEFAULT 0, "duration" INTEGER NOT NULL DEFAULT 0, "coverArt" TEXT, "navidromeAdded" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, UNIQUE("libraryId", "navidromeId"));
CREATE INDEX "Album_libraryId_title_idx" ON "Album"("libraryId", "title"); CREATE INDEX "Album_artistId_idx" ON "Album"("artistId");
CREATE TABLE "Track" ("id" UUID PRIMARY KEY, "libraryId" UUID NOT NULL REFERENCES "Library"("id") ON DELETE CASCADE ON UPDATE CASCADE, "artistId" UUID NOT NULL REFERENCES "Artist"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "albumId" UUID NOT NULL REFERENCES "Album"("id") ON DELETE CASCADE ON UPDATE CASCADE, "navidromeId" TEXT NOT NULL, "title" TEXT NOT NULL, "discNumber" INTEGER NOT NULL DEFAULT 1, "trackNumber" INTEGER, "duration" INTEGER NOT NULL DEFAULT 0, "suffix" TEXT, "contentType" TEXT, "bitRate" INTEGER, "path" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, UNIQUE("libraryId", "navidromeId"));
CREATE INDEX "Track_albumId_discNumber_trackNumber_idx" ON "Track"("albumId", "discNumber", "trackNumber"); CREATE INDEX "Track_libraryId_title_idx" ON "Track"("libraryId", "title");
CREATE TABLE "MusicRequest" ("id" UUID PRIMARY KEY, "libraryId" UUID NOT NULL REFERENCES "Library"("id") ON DELETE CASCADE ON UPDATE CASCADE, "artist" TEXT NOT NULL, "album" TEXT NOT NULL, "requesterId" UUID NOT NULL REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "claimantId" UUID REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE, "fulfillerId" UUID REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE, "fulfilledAlbumId" UUID REFERENCES "Album"("id") ON DELETE SET NULL ON UPDATE CASCADE, "status" "RequestStatus" NOT NULL DEFAULT 'OPEN', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "claimedAt" TIMESTAMP(3), "fulfilledAt" TIMESTAMP(3), "cancelledAt" TIMESTAMP(3));
CREATE INDEX "MusicRequest_libraryId_status_createdAt_idx" ON "MusicRequest"("libraryId", "status", "createdAt");
CREATE TABLE "UploadBatch" ("id" UUID PRIMARY KEY, "libraryId" UUID NOT NULL REFERENCES "Library"("id") ON DELETE CASCADE ON UPDATE CASCADE, "uploaderId" UUID NOT NULL REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "requestId" UUID REFERENCES "MusicRequest"("id") ON DELETE SET NULL ON UPDATE CASCADE, "status" "UploadStatus" NOT NULL DEFAULT 'STAGED', "stagingPath" TEXT NOT NULL, "error" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" TIMESTAMP(3));
CREATE INDEX "UploadBatch_libraryId_createdAt_idx" ON "UploadBatch"("libraryId", "createdAt");
CREATE TABLE "UploadFile" ("id" UUID PRIMARY KEY, "uploadBatchId" UUID NOT NULL REFERENCES "UploadBatch"("id") ON DELETE CASCADE ON UPDATE CASCADE, "originalName" TEXT NOT NULL, "stagedName" TEXT NOT NULL, "canonicalPath" TEXT, "detectedArtist" TEXT, "detectedAlbum" TEXT, "detectedTitle" TEXT);
CREATE INDEX "UploadFile_uploadBatchId_idx" ON "UploadFile"("uploadBatchId");
CREATE TABLE "Contribution" ("id" UUID PRIMARY KEY, "libraryId" UUID NOT NULL REFERENCES "Library"("id") ON DELETE CASCADE ON UPDATE CASCADE, "contributorId" UUID NOT NULL REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "uploadBatchId" UUID NOT NULL REFERENCES "UploadBatch"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "albumId" UUID NOT NULL REFERENCES "Album"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE("uploadBatchId", "albumId"));
CREATE INDEX "Contribution_libraryId_createdAt_idx" ON "Contribution"("libraryId", "createdAt");
CREATE TABLE "ContributionTrack" ("contributionId" UUID NOT NULL REFERENCES "Contribution"("id") ON DELETE CASCADE ON UPDATE CASCADE, "trackId" UUID NOT NULL REFERENCES "Track"("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY("contributionId", "trackId"));
CREATE TABLE "ActivityEvent" ("id" UUID PRIMARY KEY, "libraryId" UUID NOT NULL REFERENCES "Library"("id") ON DELETE CASCADE ON UPDATE CASCADE, "actorId" UUID REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE, "type" "ActivityType" NOT NULL, "payload" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "ActivityEvent_libraryId_createdAt_idx" ON "ActivityEvent"("libraryId", "createdAt");
CREATE TABLE "HiddenAlbum" ("userId" UUID NOT NULL REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE, "libraryId" UUID NOT NULL REFERENCES "Library"("id") ON DELETE CASCADE ON UPDATE CASCADE, "albumId" UUID NOT NULL REFERENCES "Album"("id") ON DELETE CASCADE ON UPDATE CASCADE, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY("userId", "albumId"));
CREATE INDEX "HiddenAlbum_libraryId_idx" ON "HiddenAlbum"("libraryId");
